# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [2]:
# Create and solve the relevant system of equations
import numpy as np
A = np.array([[29, 41], [23, 41]])
B = np.array([[490], [448]])

np.linalg.solve(A,B)

array([[7.],
       [7.]])

In [3]:
# Describe your result
'''Each bag of coffe or tea costs $7.

To test we can multiply 29*7 + 41*7 = 203 + 287 + 490'''

'Each bag of coffe or tea costs $7.\n\nTo test we can multiply 29*7 + 41*7 = 203 + 287 + 490'

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [4]:
# Create and solve the relevant system of equations
A = np.array([[12,3], [8,3]])
B = np.array([[162], [122]])

np.linalg.solve(A,B)


array([[10.],
       [14.]])

In [5]:
# Describe your result
'''
$10 for children
$14 for adults
'''

'\n$10 for children\n$14 for adults\n'

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [7]:
# Create and solve the relevant system of equations
'''
O = Number of Onions
T = Number of Tomatoes
C = Number of Carrots

.5O + .75T + 1.5C = 5.75

        2T        = O
 -O +   2T        = 0   # There are 2x as many Tomatoes as Onions

  O +    T +    C = 7  # There are 7 total vegetables

'''

A = np.array([[0.5,0.75,1.25],
              [-1 ,2   ,0   ],
              [1  ,1   ,1   ]])

B = np.array([[5.25],[0],[7]])

x = np.linalg.solve(A,B)
x

array([[3.5 ],
       [1.75],
       [1.75]])

In [13]:
# Describe your result
'''
The recipe calls for
3.5 Onions
1.75 Tomatoes
1.75 Carrots
'''

# Check results
print(x.sum() == 7)
print(2 * x[1] == x[0])

True
[ True]


## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [19]:
# Create and solve the relevant system of equations
'''
x1 = 1bed rent
x2 = 2bed rent
x3 = 3bed rent

    x1  +     x2  +     x3  = 1240

0.1(x1) + 0.2(x2) + 0.3(x3) = 276

                      2(x1) = x3
  2(x1) + 0  (x2) -     x3  = 0
'''

A = np.array([[1  , 1  , 1],
              [0.1, 0.2, 0.3],
              [2  , 0  , -1  ]])

B = np.array([[1240], [276], [0]])

np.linalg.solve(A, B)

array([[280.],
       [400.],
       [560.]])

In [ ]:
# Describe your result
'''
One bedroom apartment rent = 280
Two bedroom apartment rent = 400
Three bedroom apartent rent = 560
'''

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 